version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./docker/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector http://localhost:8888/metrics
      - "8889:8889" # Prometheus exporter metrics http://localhost:8889/metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zpages extension
  prometheus:
    image: prom/prometheus:latest
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./docker/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090" # http://localhost:9090
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    user: root
    volumes:
      - ./docker/tempo.yaml:/etc/tempo.yaml
      - ./var/tempo:/tmp/tempo
    ports:
      - "3200:3200" # tempo
      - "1111:4317" # otlp grpc
      - "1112:4318" # otlp http

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./docker/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000" # http://localhost:3000/explore
