receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:
  memory_limiter:
    limit_mib: 4000
    spike_limit_mib: 500
    check_interval: 1s

exporters:
  # Tempo exporter
  otlp/tempo:
    endpoint: "tempo:4317"  # Use gRPC endpoint
    tls:
      insecure: true

  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "otel_collector"

  # Logging exporter to debug trace processing
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo, logging]  # Add logging to see trace activity
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

